server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: ORDINARY_FRAMEWORK_ADMIN
    password: ORDINARY_FRAMEWORK_ADMIN
  redis:
    host: 127.0.0.1
    port: 6379

# 权限认证
auth:
  enable: true
  add-path-patterns:
    - /api/**
  exclude-path-patterns:
    - /api/system/auth/**
    - /api/common/**

# swagger文档
swagger:
  enable: true
  base-package: io.github.ordinarykai

# 文件上传
file-upload:
  path: /application/mine/ordinary-framework-admin/upload/
  url: localhost:${server.port}/upload

logback:
  file-path: /application/mine/ordinary-framework-admin/logs/  # 日志文件存储目录