spring:
  application:
    name: ordinary-framework-admin
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

mybatis-plus:
  type-aliases-package: com.rzl.entity
  mapper-locations: classpath:/xml/*Mapper.xml
  generator:
    # 代码生成
    code:
      author: wukai
      output-dir: /application/mine/ordinary-framework-admin/generator/
      parent: io.github.ordinarykai
      id-type: input
      schema-name: ORDINARY_FRAMEWORK_ADMIN
    # 数据库文档生成
    doc:
      output-dir: /application/mine/ordinary-framework-admin/doc/
      file-name: 数据库设计文档

# api接口日志
api-log:
  enable: true
  prefix:
    - /api

logging:
  level:
    com:
      github:
        ordinarykai: INFO