server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://1.116.114.206:3306/ordinary-framework-admin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: kai
    password: qwertyuiop
  redis:
    host: 192.168.22.128
    port: 6379

# 权限认证
auth:
  enable: true
  add-path-patterns:
    - /api/**
  exclude-path-patterns:
    - /api/admin/auth/login
    - /api/admin/auth/out
    - /api/common/**

# swagger文档
swagger:
  enable: true
  base-package: com.github.ordinarykai

# 文件上传
file-upload:
  path: D:/
  url: localhost:8080/upload

logback:
  file-path: /application/popup-windows/logs/  # 日志文件存储目录