spring:
  application:
    name: ordinary-framework-admin
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类

mybatis-plus:
  type-aliases-package: io.github.ordinarykai.entity
  mapper-locations: classpath:/xml/*Mapper.xml
  generator:
    # 代码生成
    code:
      author: wukai
      output-dir: D:/generator/code
      parent: io.github.ordinarykai
    # 数据库文档生成
    doc:
      output-dir: D:/generator/doc

sms:
  enable: true
  channel: ali_yun
  access-key-id: LTAI5tRMQdMu2tz8XwAsPzJJ
  access-key-secret: nj2nfXkpbef6eA88abZfbHeBuRPb2S
  sign-name: 阿里云短信测试
  templates:
    test: SMS_154950909
  ali-extend:
    end-point: cn-hangzhou

# api接口日志
api-log:
  enable: true
  prefix:
    - /api

logging:
  level:
    com:
      github:
        ordinarykai: INFO