server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ordinary-framework-admin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379

# 权限认证
auth:
  enable: true
  add-path-patterns:
    - /api/**
  exclude-path-patterns:
    - /api/system/auth/**
    - /api/common/**

# swagger文档
swagger:
  enable: true
  base-package: io.github.ordinarykai

# 文件上传
file-upload:
  path: E:/application/mine/ordinary-framework-admin/upload/
  url: localhost:${server.port}/upload

logback:
  file-path: /application/mine/ordinary-framework-admin/logs/  # 日志文件存储目录